env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser

brews:
  - tap:
      owner: yu1hpa
      name: homebrew-ctftime-cli
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    description: "CTF TIME CLI"
    homepage: "https://github.com/yu1hpa/ctftime-cli"
    folder: Formula
    install: |
      bin.install "ctftime-cli"
    test: |
      system "#{bin}/ctftime-cli version"

